### ISSUE TITLE
Add notice to documentation

### ISSUE THREAD

**Issue by ACH1980** [TeleIO/Telemachus-1#67]
Hi, I think it would be great to add a notice to the documentation (forum Post) that you shouldn't start KSP while Telemachus Site is open and running. Had several crashs yesterday at startup but couldn't figure out what was the unknown variable that decided if KSP would crash at startup. Until I found the following lines in the log short before crashing:
```
Obtained 7 stack frames.
#0  0x000000009de621 in (Unknown)
#1  0x00000000d65d1b in (Unknown)
#2  0x00000000e0fe2a in (Unknown)
#3  0x000000406cd752 in (wrapper managed-to-native) UnityEngine.Object:FindObjectsOfType (System.Type)
#4  0x00000040a4930e in Telemachus.DataLinkResponsibility:process (WebSocketSharp.Net.HttpListenerRequest,WebSocketSharp.Net.HttpListenerResponse)
#5  0x00000040a4874e in Telemachus.KSPWebServerDispatcher:DispatchRequest (object,WebSocketSharp.Server.HttpRequestEventArgs)
#6  0x00000040a4855b in WebSocketSharp.Server.HttpServer:processRequest (WebSocketSharp.Net.HttpListenerContext)
PartLoader: Compiling Internal Prop 'Squad/Props/buttonsGeneric/clusterButtons/genericClusterButtons'
```
After that I tried several times with Telemachus Site running and with paused execution in Firefox Debugger and when it ran KSP crashed every time, but when it didn't ran KSP didn't crash...

I don't think it would be a good idea to make a fix for this as I think it would be more work than use.

**Comment by SolAstrius** [comment]
This issue doesn't have a body or any comments — could you clarify what notice or documentation change you had in mind? Happy to address it if you can describe what's needed.

**Comment by SolAstrius** [comment]
Hi\! This should be fixed in v1.10.0 — commit 53d795b resolved the CameraCaptureManager singleton NullRef that caused the FindObjectsOfType crash during PartLoader initialization. Could you let us know which version you're on? If you're already on 1.10.0 and still seeing this, we'd love to get your logs.
